# Name of your workflow
name: Clang Format
# Define the trigger event(s)
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs:

    # Job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - name: Say hello
            run: echo "Hello, GitHub Actions!"

    # Job to build and test our C code
    build-and-test:
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:
        
            # Use github.com/actions/checkout to check out this repo
          - name: Check out this repo
            uses: actions/checkout@v3
            
            # Install necessary packages
          - name: Install dependencies
            run: sudo apt install clang-format
            
            # See where we are in the VM
          - run: ls
          - run: pwd

          - run: cd /home/runner/work/freeRTOS-pp/freeRTOS-pp/src/
