# workflow name
name: Doxygen GitHub Pages Deploy Action v2

# trigger event(s):
on: [push]

jobs:
  run-doxygen:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Installing Doxygen..."
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: install doxygen
        run: sudo apt-get install doxygen\
        
      - run: pwd
      
      - run: echo "Creating documentation..."

      - name: create documentation
        run: doxygen Doxyfile
        
      - run: ls        
